export const GET_COVID_REPORTS_DATA_REQUEST = "GET_COVID_REPORTS_DATA_REQUEST";
export const GET_COVID_REPORTS_DATA_RESPONSE = "GET_COVID_REPORTS_DATA_RESPONSE";
export const SEARCH_KEY = "SEARCH_KEY";
export const DISTRICT_DETAILS_OF_STATE="DISTRICT_DETAILS_OF_STATE";